name: Karma Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install Chromium
        run: sudo apt install chromium-browser
      - name: Install Node dependencies
        run: npm install
      - name: Run Karma Tests
        run: npm run test:ci
        env:
          CI: true
